## Input Configuration ##

## Scroll Wheel ##
WHEEL_RIGHT      add volume 2
WHEEL_LEFT       add volume -2
WHEEL_DOWN       seek -10         # seek 10 seconds backward
WHEEL_UP         seek 10          # seek 10 seconds forward

## Add Sharpness to Video ##
= add sharpen +0.05
- add sharpen -0.05

## Increase/decrease subtitle font size ##
#ALT+g add sub-scale +0.025 #Using sub-scale.lua
#ALT+f add sub-scale -0.025 #Using sub-scale.lua

## Increase/decrease subtitle height ##
r add sub-pos -0.25 #Using sub-scale.lua
t add sub-pos +0.25 #Using sub-scale.lua

## Previous & Next Track ##
#XF86AudioPrev playlist-prev
#XF86AudioNext playlist-next

## Change Embedded Subs Blur ##
alt+ctrl+u cycle-values sub-gauss "0.0" "0.5" "1.0" "1.5" "2.0"
## Change Subs To Monochrome ##
alt+u cycle-values sub-gray "yes" "no"

## .ass Subtitles Override ##
alt+shift+u cycle-values sub-ass-override "strip" "force" "yes" "no"

## Change Aspect Ratio with Shift+A ##
A cycle-values video-aspect-override "1.777" "1.333" "2.35:1" "1.576" "-1"

## Rotate Video 90 degrees ## controlled by rotate.lua now
#ctrl+r cycle_values video-rotate 90 180 270 0 

## Keys to ignore ##
F ignore # Changed subtitle size +0.100
G ignore # Changed subtitle size -0.100
E ignore # Specify the edition (set of chapters) to us
ENTER ignore # Skipped current file

## Shuffle Playlist ##
alt+k playlist-shuffle ; show-text "${playlist}" 4000

## Show Playlist ##
ctrl+alt+l show-text "${playlist}" 3000

## Audio To Mono ##
alt+shift+m af toggle "lavfi=[pan=1c|c0=1*c0+1*c1]" ; show-text "Audio mix set to Mono"

## Audio Equalizers ##
F1 cycle-values af  "dynaudnorm=g=7" "dynaudnorm=g=5" "dynaudnorm=g=3" ""
F2 cycle-values af  "loudnorm=I=-16:TP=-1.5:LRA=11" ""
F3 cycle-values af  "lavfi=[dynaudnorm=f=75:g=25:n=0:p=0.58],volume=softclip=yes" "" 

## Loop Playlist ##
ctrl+l cycle-values loop-playlist "inf" "no" 

## Clear GLSL shaders ##
#CTRL+0 change-list glsl-shaders clr ""
