## No OSC because using scripts/osc.lua instead ##
no-osc

## Title Bar ##
#title='(${playlist-pos-1}/${playlist-count}) ${filename/no-ext} ${?chapter-metadata/title:[${chapter-metadata/title}]} - mpv'

## Show file track and title on media open/change ##
#osd-playing-msg = "${osd-ass-cc/0}{\\an9}${osd-ass-cc/1}${?metadata/track: ${metadata/track} }${?metadata/PART_NUMBER: ${metadata/PART_NUMBER} }${media-title}"

vo=gpu-next
gpu-api=vulkan
hwdec=vulkan
#gpu-context=waylandvk
tone-mapping=bt.2390
hdr-compute-peak=yes
target-colorspace-hint=no
video-sync=display-resample
interpolation=yes
tscale=oversample

## Audio settings ##
volume=100
volume-max=250
alang=Japanese:Stereo,Japanese,jpn,ja,English:Stereo,English,eng,en
#af=dynaudnorm=g=7

## Subtitle settings ##
slang=English,english,eng,en,enGB,enUS
#sub-file-paths=Sub:Subs:Subtitles:Anime ## USING A .lua File In Scripts Folder By The Same Name - Is To Fix Not Searching Folders For Subtitles On Linux
sub=auto
sub-auto=fuzzy
sub-font="Trebuchet MS"
sub-color="#f7f7f7"
sub-border-color="#121212"
sub-shadow-color="#404040"
sub-gauss=0.8
sub-pos=103.5
sub-scale=1.000
sub-border-size=3.6
#sub-shadow-offset=1

## OSD settings ##
osd-blur=1.4
osd-font="Trebuchet MS"
osd-font-size=20
osd-color="#ff536586"
osd-selected-color="#ff718cba"

## Screenshot settings ##
screenshot-format=png
screenshot-template=/mnt/Storage/Pictures/mpv/mpv-%n

## Window settings ##
#cursor-autohide=number
no-keepaspect-window
#monitoraspect=1.777
autofit-larger=40%x40%
autofit-smaller=40%x40%
geometry=50%:50%
#no-border

## Autoload Playlist ##
autocreate-playlist=same
directory-filter-types=video,audio,image
directory-mode=ignore
video-exts=3g2,3gp,avi,flv,m2ts,m4v,mj2,mkv,mov,mp4,mpeg,mpg,ogv,rmvb,ts,webm,wmv,y4m
image-exts=avif,bmp,gif,j2k,jp2,jpeg,jpg,jxl,png,svg,tga,tif,tiff,webp
audio-exts=aiff,ape,au,flac,m4a,mka,mp3,oga,ogg,ogm,opus,wav,wma

## Playlist Format ##
#playlist-display-title="${filename/no-ext}"

## Key Repeat Speed ##
input-ar-rate=14
input-ar-delay=150

## Miscellaneous settings ##
ytdl-format=bestvideo[height<=?1080]+bestaudio/best
force-seekable=yes
keep-open=yes
force-window=yes
idle

# Unknown and custom settings

# Extensions - Do not add custom settings that are not extension related below this line.
[extension.gif]
loop-file=inf

## Metadata In Title for Video Files ##
#[extension.mp4, extension.mkv, extension.avi, extension.flv]
#title='(${playlist-pos-1}/${playlist-count}) ${filename/no-ext} ${?chapter-metadata/title:[${chapter-metadata/title}]} - mpv'

## Metadata In Title for Audio Files ##
#[extension.aac, extension.mp3, extension.m4a, extension.flac, extension.wav, extension.wma]
#title='(${playlist-pos-1}/${playlist-count}) ${?metadata/track:${metadata/track} }${media-title} ${?chapter-metadata/title:[${chapter-metadata/title}]}${?metadata/artist:[${metadata/artist} - ${?metadata/album:${metadata/album} - ${?metadata/date:${metadata/date} - ${audio-bitrate}]}]} - mpv'

#-----------------------------PROFILES-----------------------------#

[light]
profile=gpu
hwdec=vulkan
vo=gpu
video-sync=audio
interpolation=no
deband=no
tscale=linear
scale=bilinear
dscale=bilinear
fbo-format=rgb32
