# Options
# -------

scalewindowed=0.9
scalefullscreen=0.9

## Show Clock Before Title on OSC ##
#title=${clock} | ${?metadata/track: ${metadata/track} }${?metadata/PART_NUMBER: ${metadata/PART_NUMBER} }${media-title}${?chapter-metadata/title: [${chapter-metadata/title}]}
#title=${clock} | ${media-title}${?chapter-metadata/title: [${chapter-metadata/title}]}
title=${media-title}

## Layout ##
layout=bottombar
seekbarstyle=bar

## Show Full Length Of Media ##
timetotal=yes

## Only Show OSD When Hovering Over It ##
deadzonesize=1.0

## Reverse Scroll Wheel Direction On OSC Audio and Sub Track Selection ##
audio_track_wheel_down_command=cycle audio down
audio_track_wheel_up_command=cycle audio

sub_track_wheel_down_command=cycle sub down
sub_track_wheel_up_command=cycle sub

## Custom Buttons ##
custom_button_1_content=V
custom_button_1_mbtn_mid_command=set vid 1; show-text "reset to video track 1" 3000
custom_button_1_mbtn_left_command=show-text ${track-list/video} 3000  # Shows all video tracks
custom_button_1_mbtn_right_command=cycle video  # Cycles through video tracks

## Menu Button ##
menu_mbtn_right_command=script-binding select/menu; script-message-to osc osc-hide
menu_mbtn_left_command=show-text ${playlist} 3000
menu_mbtn_mid_command=show-text ${path} 3000

## Restore Old OSC Binds ##
title_mbtn_mid_command=
play_pause_mbtn_mid_command=
play_pause_mbtn_right_command=
fullscreen_mbtn_right_command=
volume_mbtn_right_command=

# restore playlist_osd=yes behavior
playlist_prev_mbtn_left_command=playlist-prev; show-text ${playlist} 3000
playlist_next_mbtn_left_command=playlist-next; show-text ${playlist} 3000

# restore chapter_osd=yes behavior
chapter_prev_mbtn_left_command=no-osd add chapter -1; show-text ${chapter-list} 3000
chapter_next_mbtn_left_command=no-osd add chapter 1; show-text ${chapter-list} 3000

# restore behavior before select.lua usage
playlist_prev_mbtn_right_command=show-text ${playlist} 3000
playlist_next_mbtn_right_command=show-text ${playlist} 3000

title_mbtn_left_command=show-text "${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${media-title}"
title_mbtn_right_command=show-text ${filename}

chapter_prev_mbtn_right_command=show-text ${chapter-list} 3000
chapter_next_mbtn_right_command=show-text ${chapter-list} 3000

audio_track_mbtn_right_command=cycle audio down
audio_track_mbtn_mid_command=show-text ${track-list/audio} 3000

sub_track_mbtn_right_command=cycle sub down
sub_track_mbtn_mid_command=show-text ${track-list/sub} 3000
